// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddToProjectPopup: typeof import('./src/components/AddToProjectPopup.vue')['default']
    AppChart: typeof import('./src/components/AppChart.vue')['default']
    AppModal: typeof import('./src/components/AppModal.vue')['default']
    AppProjects: typeof import('./src/components/AppProjects.vue')['default']
    AppTasks: typeof import('./src/components/AppTasks.vue')['default']
    AppTitle: typeof import('./src/components/AppTitle.vue')['default']
    BaseViewProject: typeof import('./src/components/BaseViewProject.vue')['default']
    BaseViewTask: typeof import('./src/components/BaseViewTask.vue')['default']
    ChoreButton: typeof import('./src/components/buttons/ChoreButton.vue')['default']
    CurrentTask: typeof import('./src/components/CurrentTask.vue')['default']
    MiniLabel: typeof import('./src/components/slots/MiniLabel.vue')['default']
    NewProjectButton: typeof import('./src/components/buttons/new-buttons/NewProjectButton.vue')['default']
    NewTaskButton: typeof import('./src/components/buttons/new-buttons/NewTaskButton.vue')['default']
    Paginate: typeof import('./src/components/Paginate.vue')['default']
    PomoCountSetter: typeof import('./src/components/PomoCountSetter.vue')['default']
    Project: typeof import('./src/components/buttons/Project.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveButton: typeof import('./src/components/buttons/SaveButton.vue')['default']
    SidebarItem: typeof import('./src/components/slots/SidebarItem.vue')['default']
    Subchore: typeof import('./src/components/Subchore.vue')['default']
    Subchores: typeof import('./src/components/Subchores.vue')['default']
    Tags: typeof import('./src/components/buttons/Tags.vue')['default']
    Task: typeof import('./src/components/buttons/Task.vue')['default']
    TheAlerts: typeof import('./src/components/TheAlerts.vue')['default']
    TheProjectModal: typeof import('./src/components/TheProjectModal.vue')['default']
    TheProjectModalBody: typeof import('./src/components/TheProjectModalBody.vue')['default']
    TheSettings: typeof import('./src/components/TheSettings.vue')['default']
    TheSidebar: typeof import('./src/components/TheSidebar.vue')['default']
    TheTaskModal: typeof import('./src/components/TheTaskModal.vue')['default']
    TheTaskModalBody: typeof import('./src/components/TheTaskModalBody.vue')['default']
    TheTimer: typeof import('./src/components/TheTimer.vue')['default']
    TheUpperMenu: typeof import('./src/components/TheUpperMenu.vue')['default']
    Title: typeof import('./src/components/slots/Title.vue')['default']
    UnauthedChart: typeof import('./src/components/UnauthedChart.vue')['default']
    UnauthedLogin: typeof import('./src/components/UnauthedLogin.vue')['default']
  }
}
