# Generated by Django 4.0.1 on 2022-07-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_streak_alter_project_tasks_alter_tag_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='in_projects', to='api.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='subtasks',
            field=models.ManyToManyField(blank=True, related_name='belongs_to', to='api.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='has', to='api.Tag'),
        ),
    ]
