# Generated by Django 4.1.1 on 2022-09-11 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_task_in_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='streak',
            new_name='current_task_id',
        ),
    ]
