# Generated by Django 4.1.1 on 2022-09-17 19:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='day',
            field=models.DateField(default=django.utils.timezone.now, unique=True),
        ),
    ]
