# Generated by Django 4.1.1 on 2022-09-18 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_stats_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stats',
            old_name='done',
            new_name='chores_done',
        ),
    ]
