# Generated by Django 4.1.1 on 2022-09-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_user_auto_start_breaks_user_auto_start_pomos_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_mode_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mode',
            name='short_break',
            field=models.IntegerField(default=5),
        ),
    ]
