# Generated by Django 4.1.1 on 2022-10-22 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_task_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='minutes',
        ),
    ]
