# Generated by Django 4.1.1 on 2022-11-12 03:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_tag_name_alter_tag_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='stats',
            unique_together={('day', 'user')},
        ),
    ]
