# Generated by Django 4.1.1 on 2022-11-25 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_stats_day_alter_stats_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mode',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
