# Generated by Django 4.1.5 on 2023-04-04 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0020_task_parent_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="parent_task",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subtasks",
                to="api.task",
            ),
        ),
        migrations.DeleteModel(
            name="Subtask",
        ),
    ]
