name: Django Testing CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    

jobs:
  test_project:
    runs-on: ubuntu-latest
    # If title contains bypass do not run
    # if: "!contains(github.event.pull_request.title, '[bypass]')"
    
    # Run if there are changes made to the api directory
    # if: 'git diff --name-only ${{ github.base_ref }}..${{ github.head_ref }} | grep -qE "^backend/"'
    # if: git diff --name-only ${{ github.base_ref }}..${{ github.head_ref }} | grep -qE "^api/"
    if: github.event.push && github.event.ref == 'refs/heads/master' && !git diff --quiet api/
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install "python-dotenv[cli]"
        dotenv set SECRET_KEY ${{ secrets.SECRET_KEY }}
        dotenv set ALLOWED_HOSTS ${{ secrets.ALLOWED_HOSTS }}
    - name: Run Tests
      run: |
        python manage.py test
